"""H-30 — immutable pinned-SHA release / convergence gate.

One orchestration entry point for the full release gate. Every run:

1. pins ``HEAD`` once at the start;
2. refuses a dirty worktree (uncommitted or untracked changes that would make
   the certified tree un-reproducible);
3. re-checks that ``HEAD`` has not moved and the tree is still clean before
   every named phase and after the last phase;
4. records per-phase evidence (command, exit code, duration, head sha, log
   excerpt) so certification claims can be audited later.

This module is the *orchestration* for H-30. Individual phase payloads
(OpenAPI generation, dependency upgrades, coverage policy, scale tests) may
be owned by satellite lanes; the gate only requires that each phase name is
present, ordered, and fail-closed.

Do not treat a curated subset (e.g. ``scripts/certify-omniagentos.sh``) as a
substitute for this gate. Curated suites are component probes; this gate is
the release signal.

Usage::

    python -m omniagentos.harnesses.release_gate --list
    python -m omniagentos.harnesses.release_gate --dry-run
    python -m omniagentos.harnesses.release_gate --phases ruff,format,mypy
    python -m omniagentos.harnesses.release_gate   # full gate (resource-heavy)

Environment:

    OMNIAGENTOS_PYTHON          Interpreter for phase commands (default: project
                                ``.venv/bin/python``; never a bare PATH python)
    OMNIAGENTOS_VAR_DIR         Evidence root (default: <repo>/var)
    RELEASE_GATE_ALLOW_DIRTY    Set to ``1`` only for local debugging — never
                                for certification. Evidence records the override.
    RELEASE_GATE_LIVE           Include live/restart phases (default: 1 for full)
    RELEASE_GATE_LOAD           Include load/contention phases (default: 1 for full)

The gate *exports* ``OMNIAGENTOS_REQUIRE_PG=1`` to every phase subprocess: a
certification run must not be able to go green because PostgreSQL-backed tests
skipped themselves. See :func:`certification_env`.
"""

from __future__ import annotations

import argparse
import itertools
import json
import os
import subprocess
import sys
import time
import uuid
from collections.abc import Callable, Mapping, Sequence
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from omniagentos.knowledge.contracts import ENV_REQUIRE_PG
from omniagentos.path_containment import inode_relative_parts_anchored

# Monotonic per-process sequence so two evidence paths minted in the same
# microsecond by the same process can never collide.
_EVIDENCE_SEQ = itertools.count()

# ---------------------------------------------------------------------------
# Named phases — order is the certification order. Names are stable contract.
# ---------------------------------------------------------------------------

PhaseStatus = Literal["passed", "failed", "skipped", "refused", "planned"]
#: ``simulated`` is not a softer ``passed``: it marks a run whose interpreter was
#: never verified (an injected runner, or verification explicitly disabled), so
#: the record cannot be read as a certification. Only ``passed`` may mean that.
GateStatus = Literal["passed", "failed", "refused", "planned", "simulated"]

# Core always-on phases of the immutable full gate.
CORE_PHASE_NAMES: tuple[str, ...] = (
    "backend",
    "dashboard_unit",
    "dashboard_lint",
    "dashboard_build",
    "e2e",
    "ruff",
    "format",
    "mypy",
    "migrations",
    "api_contracts",
    "dependency_scan",
)

# Conditional phases — still named in the full plan; may skip with evidence
# when the operator explicitly disables them (not a silent omission).
CONDITIONAL_PHASE_NAMES: tuple[str, ...] = (
    "live_restart",
    "load_contention",
)

ALL_PHASE_NAMES: tuple[str, ...] = CORE_PHASE_NAMES + CONDITIONAL_PHASE_NAMES

# North Star profiles remain opt-in phase sets: adding them to the immutable
# full-gate table would silently change H-30's release contract. Makefile owns
# the thin operator targets; this harness owns their pinned-SHA PhaseSpec shape.
NORTHSTAR_PHASE_SET_NAMES: tuple[str, ...] = ("t1", "t2")

# --- satellite-owned payload handoff --------------------------------------
#
# The gate names these phases and requires them to be present, ordered and
# fail-closed; the satellites own what the payload *does*.
#
# S19A owns ``api_contracts``. Its canonical surface is the committed
# whole-API artifact ``contracts/openapi.json``, regenerated by
# ``scripts/generate_openapi.py``, with presence + drift enforced by
# ``tests/api/test_openapi_contract.py``. That test fails closed when the
# artifact is absent (CI must never auto-seed it) and when the live schema
# drifts from the committed contract. Running the test path — rather than a
# bespoke existence check — is what keeps this gate aligned with the satellite
# instead of asserting a filename the satellite does not produce.
API_CONTRACT_ARTIFACT = "contracts/openapi.json"
API_CONTRACT_GENERATOR = "scripts/generate_openapi.py"
API_CONTRACT_TEST = "tests/api/test_openapi_contract.py"

# S19B owns the ``live_restart`` and ``load_contention`` payloads (coverage
# policy, scale gates, what the tests actually assert). The gate pins only the
# marker contract below; it must not reach into S19B's policy modules.
#
# ``smoke`` and ``perf`` are pre-existing repository-wide markers carried by
# unrelated tests, so selecting on them alone certifies "some smoke test ran",
# not "S19B's restart payload ran": delete the payload entirely and the phase
# still passes on somebody else's test. Each phase therefore selects the
# *conjunction* of the infrastructure marker and a payload marker that only
# S19B applies. That keeps the coupling surface exactly where the documented
# handoff puts it — a pytest marker — while making the phase fail closed: with
# no test carrying the payload marker the selection is empty, and the
# no-silent-skip guard refuses an empty selection rather than certifying it.
LIVE_RESTART_MARKER = "smoke"
LOAD_CONTENTION_MARKER = "perf"

#: Applied by S19B to the specific tests each phase exists to certify.
LIVE_RESTART_PAYLOAD_MARKER = "s19b_live_restart"
LOAD_CONTENTION_PAYLOAD_MARKER = "s19b_load_contention"

#: The ``-m`` expressions the phases run. Both conjuncts are required: the
#: infrastructure marker keeps the run under the existing execution policy, and
#: the payload marker is what makes the evidence about S19B's payload.
LIVE_RESTART_SELECTION = f"{LIVE_RESTART_MARKER} and {LIVE_RESTART_PAYLOAD_MARKER}"
LOAD_CONTENTION_SELECTION = f"{LOAD_CONTENTION_MARKER} and {LOAD_CONTENTION_PAYLOAD_MARKER}"

# Loaded with ``-p`` into every phase whose entire selection is one required
# payload. pytest exits 0 when all selected tests skip and when a marker
# deselects everything, so without this a missing S19A/S19B payload — or a
# module that skips itself — certifies as "passed".
NO_SILENT_SKIP_PLUGIN = "omniagentos.harnesses.no_silent_skip"

#: Bounded regeneration attempts for an auto-named evidence file.
_EVIDENCE_WRITE_ATTEMPTS = 8


class ReleaseGateError(RuntimeError):
    """Base error for the release gate (dirty tree, moved HEAD, phase fail)."""


class DirtyTreeError(ReleaseGateError):
    """Worktree is dirty — certification refused."""


class MovingHeadError(ReleaseGateError):
    """HEAD moved after pin — certification refused."""


class EvidenceWriteError(ReleaseGateError):
    """The audit record could not be persisted — certification is not evidenced."""


@dataclass(frozen=True)
class PhaseSpec:
    """One named gate phase."""

    name: str
    description: str
    # argv is resolved against the repo root / python at run time.
    argv: tuple[str, ...]
    conditional: bool = False
    # Env var that must be truthy for a conditional phase to run (default on).
    enable_env: str = ""


@dataclass(frozen=True)
class PhaseEvidence:
    """Immutable record of one phase attempt."""

    name: str
    status: PhaseStatus
    pinned_sha: str
    head_sha_at_start: str
    head_sha_at_end: str
    started_at: str
    ended_at: str
    duration_ms: int
    exit_code: int | None
    command: list[str]
    detail: str = ""
    log_excerpt: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class GateEvidence:
    """Full gate run evidence — written to disk after every attempt."""

    pinned_sha: str
    status: GateStatus
    started_at: str
    ended_at: str = ""
    repo_root: str = ""
    allow_dirty: bool = False
    refuse_reason: str = ""
    phases: list[PhaseEvidence] = field(default_factory=list)
    selected_phases: list[str] = field(default_factory=list)
    python: str = ""
    require_pg: bool = False
    #: Whether the interpreter that ran the phases was actually verified. False
    #: for an injected runner or ``verify_interpreter=False`` — a record that
    #: proves nothing about a real environment, and must not read like one.
    interpreter_verified: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "pinned_sha": self.pinned_sha,
            "status": self.status,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "repo_root": self.repo_root,
            "allow_dirty": self.allow_dirty,
            "refuse_reason": self.refuse_reason,
            "selected_phases": list(self.selected_phases),
            "python": self.python,
            "require_pg": self.require_pg,
            "interpreter_verified": self.interpreter_verified,
            "phases": [p.to_dict() for p in self.phases],
        }


# Type for injectable command runner: (argv, cwd) -> (exit_code, combined_output)
CommandRunner = Callable[[Sequence[str], Path], tuple[int, str]]


def _utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _truthy(value: str | None) -> bool:
    if value is None:
        return False
    return value.strip().lower() in {"1", "true", "yes", "on"}


def default_repo_root(start: Path | None = None) -> Path:
    """Walk up from *start* (or this file) to the repository root."""
    here = (start or Path(__file__).resolve()).resolve()
    if here.is_file():
        here = here.parent
    for candidate in (here, *here.parents):
        if (candidate / "pyproject.toml").is_file() and (candidate / "omniagentos").is_dir():
            return candidate
    return Path.cwd().resolve()


class InterpreterError(ReleaseGateError):
    """Python interpreter cannot be verified as project-local."""


def normalize_executable(path: str | Path) -> Path:
    """Absolute, normalized interpreter path that *preserves the venv symlink*.

    ``Path.resolve()`` must never be used on an interpreter path. A virtualenv's
    ``bin/python`` is normally a symlink to the base interpreter (uv, pyenv and
    ``python -m venv --symlinks`` all do this). Resolving it yields the *bare
    base interpreter*, whose ``sys.prefix`` is the standalone install rather
    than the project venv — so none of the project's dependencies (pytest,
    ruff, mypy, psycopg) are importable and the gate would certify under an
    interpreter that cannot even run its own phases.

    Only the parent directory is resolved (normalizing ``..`` and intermediate
    symlinks); the final component is kept verbatim so CPython's ``site``
    initialization still finds ``pyvenv.cfg`` next to the executable.
    """
    p = Path(path)
    if not p.is_absolute():
        p = Path.cwd() / p
    try:
        parent = p.parent.resolve()
    except OSError:  # pragma: no cover - unreadable parent
        parent = p.parent
    return parent / p.name


def _is_within(path: Path, root: Path) -> bool:
    """True when *path* lies under *root*, tolerating symlinked repo roots."""
    return inode_relative_parts_anchored(path, root) is not None


def resolve_python(
    env: Mapping[str, str] | None = None,
    *,
    repo_root: Path | None = None,
    require_project_local: bool = True,
) -> str:
    """Pick the interpreter used for phase commands.

    The release gate must certify under the project's own interpreter, never a
    foreign Python that may have different packages or versions. When
    *require_project_local* is True (default for certification), the interpreter
    must be:

    1. Explicitly set via ``OMNIAGENTOS_PYTHON`` and executable; or
    2. The project's own ``.venv/bin/python``; or
    3. ``sys.executable`` if it lives under the repo root.

    Every branch returns a :func:`normalize_executable` path, so the selected
    interpreter keeps its virtualenv instead of collapsing into the base
    interpreter behind the symlink.

    Refuses certification with a clear error when no auditable interpreter can
    be resolved, rather than silently falling back to a random PATH python.
    """
    e = env if env is not None else os.environ
    root = (repo_root or default_repo_root()).resolve()

    # Explicit override takes priority — must be executable.
    override = (e.get("OMNIAGENTOS_PYTHON") or "").strip()
    if override:
        p = normalize_executable(override)
        if not p.is_file():
            raise InterpreterError(f"OMNIAGENTOS_PYTHON={override!r} does not exist")
        if not os.access(p, os.X_OK):
            raise InterpreterError(f"OMNIAGENTOS_PYTHON={override!r} is not executable")
        return str(p)

    # Project-local venv is the standard certified interpreter.
    venv_py = normalize_executable(root / ".venv" / "bin" / "python")
    if venv_py.is_file() and os.access(venv_py, os.X_OK):
        return str(venv_py)

    # Fallback: running interpreter if it is within the project tree.
    running = normalize_executable(sys.executable)
    if require_project_local:
        if _is_within(running, root):
            return str(running)
        raise InterpreterError(
            f"release gate requires a project-local interpreter; "
            f"sys.executable={running} is outside {root}; "
            f"set OMNIAGENTOS_PYTHON or create .venv"
        )

    # Non-certification fallback (debug/list modes).
    return str(running)


@dataclass(frozen=True)
class InterpreterProbe:
    """What a candidate interpreter actually reports about itself."""

    executable: str
    prefix: str
    base_prefix: str
    importable: dict[str, bool]

    @property
    def in_virtualenv(self) -> bool:
        """True when the interpreter is running inside a venv, not the base install."""
        return bool(self.prefix) and self.prefix != self.base_prefix


#: Modules a certifying interpreter must be able to import. These are exactly
#: the packages the gate's own phases need; psycopg is included because a
#: base-interpreter regression makes PostgreSQL-backed tests unrunnable, which
#: is the failure mode OMNIAGENTOS_REQUIRE_PG exists to surface.
REQUIRED_INTERPRETER_MODULES: tuple[str, ...] = ("pytest", "ruff", "mypy", "psycopg")


def _probe_source(modules: tuple[str, ...]) -> str:
    """Build the probe program run inside the candidate interpreter.

    Each module is genuinely ``import_module``-ed rather than merely located
    with ``find_spec``. Discoverability is not runnability: a half-installed
    wheel leaves an importable-looking package whose ``__init__`` raises (a
    ``psycopg`` without its libpq shared library is the canonical case), and
    ``find_spec`` reports it as present. That is precisely the stale or
    half-built environment this verification exists to reject, so the probe has
    to do the thing the phases will later do.

    Every exception is caught, not just ``ImportError``: a module that raises
    ``RuntimeError`` on import is just as unusable, and letting it escape would
    fail the whole probe with a traceback instead of a named missing module.
    """
    return (
        "import json,sys,importlib\n"
        "ok={}\n"
        f"for m in {modules!r}:\n"
        "    try:\n"
        "        importlib.import_module(m); ok[m]=True\n"
        "    except BaseException:\n"
        "        ok[m]=False\n"
        "print(json.dumps({'executable':sys.executable,'prefix':sys.prefix,"
        "'base_prefix':sys.base_prefix,'importable':ok}))\n"
    )


_PROBE_SRC = _probe_source(REQUIRED_INTERPRETER_MODULES)


def probe_interpreter(python: str, *, timeout: float = 60.0) -> InterpreterProbe:
    """Ask *python* about its own venv and whether the gate's tooling imports.

    Used to prove that interpreter selection did not silently degrade to a base
    interpreter that cannot run the gate's own phases.

    Every way the probe can fail is raised as :class:`InterpreterError`, which is
    the only exception :func:`run_release_gate` converts into durable refusal
    evidence. A hang, an unexecutable file, or output that is not the expected
    JSON would otherwise propagate as a raw ``TimeoutExpired``/``OSError``/
    ``ValueError`` and abort the gate with no record written at all — the run
    would leave no evidence that it had ever been attempted, which is the
    failure mode the evidence file exists to prevent.
    """
    try:
        proc = subprocess.run(  # noqa: S603 - argv is a resolved interpreter path
            [python, "-c", _PROBE_SRC],
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        raise InterpreterError(
            f"interpreter probe for {python!r} did not answer within {timeout}s; "
            f"an interpreter that cannot report on itself cannot be certified"
        ) from exc
    except OSError as exc:
        raise InterpreterError(
            f"interpreter probe for {python!r} could not be executed: {exc}"
        ) from exc
    except UnicodeDecodeError as exc:
        # ``text=True`` decodes inside ``subprocess.run``, so undecodable bytes
        # raise here rather than at the JSON step below, and would escape this
        # function as a bare ``ValueError``.
        raise InterpreterError(
            f"interpreter probe for {python!r} produced undecodable output ({exc}); "
            f"refusing to guess what it meant"
        ) from exc

    if proc.returncode != 0:
        raise InterpreterError(
            f"interpreter probe failed for {python!r} (rc={proc.returncode}): "
            f"{(proc.stderr or proc.stdout).strip()}"
        )

    # A zero exit code is not the same as a usable answer: a wrapper script, a
    # sitecustomize banner, or a shim that prints something else entirely all
    # exit 0. Parse defensively and refuse rather than crash, so the operator
    # gets refusal evidence naming the interpreter instead of a traceback.
    try:
        data = json.loads(proc.stdout)
    except ValueError as exc:
        raise InterpreterError(
            f"interpreter probe for {python!r} did not return JSON ({exc}); "
            f"output was {proc.stdout.strip()[:200]!r}"
        ) from exc
    if not isinstance(data, dict):
        raise InterpreterError(
            f"interpreter probe for {python!r} returned {type(data).__name__}, not an object"
        )
    raw_importable = data.get("importable")
    if not isinstance(raw_importable, dict):
        raise InterpreterError(
            f"interpreter probe for {python!r} returned no usable 'importable' "
            f"mapping (got {type(raw_importable).__name__}); refusing to treat an "
            f"unreadable probe as clean"
        )
    missing_keys = sorted({"executable", "prefix", "base_prefix"} - set(data))
    if missing_keys:
        raise InterpreterError(
            f"interpreter probe for {python!r} omitted {', '.join(missing_keys)}; "
            f"refusing to treat an incomplete probe as clean"
        )
    # Coercing the values would fail *open*, which is the worst direction for a
    # check whose whole job is to catch a degraded interpreter: ``bool("false")``
    # is ``True``, so a wrapper answering ``"false"`` for every module — the
    # literal report "nothing imports" — would be recorded as fully importable and
    # certified. The same applies to the identity fields: ``str(None)`` is
    # ``"None"``, a prefix that would then be compared against real paths. Demand
    # the types the probe is documented to emit and refuse anything else.
    mistyped = sorted(f"{k}={v!r}" for k, v in raw_importable.items() if not isinstance(v, bool))
    if mistyped:
        raise InterpreterError(
            f"interpreter probe for {python!r} returned non-boolean import verdicts "
            f"({', '.join(mistyped)}); refusing to guess whether that means importable"
        )
    importable = {str(k): v for k, v in raw_importable.items() if isinstance(v, bool)}
    # A verdict is only as good as its coverage: callers decide by scanning this
    # mapping for false values, so a probe that answered about *fewer* modules
    # than were asked would report "nothing missing" while leaving the rest
    # untested — an empty mapping would certify everything. Demand a verdict per
    # requested module rather than trusting the payload's shape.
    expected = set(REQUIRED_INTERPRETER_MODULES)
    unanswered = sorted(expected - set(importable))
    if unanswered:
        raise InterpreterError(
            f"interpreter probe for {python!r} returned no verdict for "
            f"{', '.join(unanswered)}; refusing to treat an incomplete probe as clean"
        )
    non_strings = sorted(
        f"{field}={data[field]!r}"
        for field in ("executable", "prefix", "base_prefix")
        if not isinstance(data[field], str)
    )
    if non_strings:
        raise InterpreterError(
            f"interpreter probe for {python!r} returned non-string interpreter "
            f"identity ({', '.join(non_strings)}); refusing to compare coerced paths"
        )
    return InterpreterProbe(
        executable=str(data["executable"]),
        prefix=str(data["prefix"]),
        base_prefix=str(data["base_prefix"]),
        importable=importable,
    )


def _is_project_venv_prefix(prefix: Path, repo_root: Path) -> bool:
    """True when prefix lies under repo_root, default_repo_root(), or project tree."""
    roots = {repo_root, default_repo_root()}
    sys_exec = Path(sys.executable)
    for candidate in (sys_exec.parent, *sys_exec.parents):
        if (candidate / "pyproject.toml").is_file() and (candidate / "omniagentos").is_dir():
            roots.add(candidate)
    for root in roots:
        if _is_within(prefix, root):
            return True
    return False


def verify_certification_interpreter(
    python: str,
    *,
    repo_root: Path,
    require_local_prefix: bool = True,
    timeout: float = 60.0,
) -> InterpreterProbe:
    """Refuse certification unless *python* really is the audited project venv.

    Path-shape checks alone are not enough. ``resolve_python`` only asks whether
    a file exists and is executable, so a stale, half-built, or symlinked
    ``.venv/bin/python`` pointing at a foreign interpreter still passes — and if
    that foreign interpreter happens to have pytest installed, the gate would
    certify against an environment nobody audited.

    The authoritative signal is what the interpreter says about *itself*:

    * ``sys.prefix != sys.base_prefix``, i.e. it is a virtualenv at all.
    * Every module in :data:`REQUIRED_INTERPRETER_MODULES` imports.
    * When *require_local_prefix* is set, ``sys.prefix`` must lie under the
      repository root. This is computed by CPython from the ``pyvenv.cfg``
      sitting next to the executable, so it cannot be forged by symlinking a
      path into the repo — a link at ``<repo>/.venv/bin/python`` pointing at
      ``/usr/bin/python3`` reports ``sys.prefix=/usr`` and is refused. Checking
      the executable path instead would be both weaker (symlink escape) and
      wrong (every venv's ``python`` is legitimately a symlink to the base
      install).

    Locality is required for the branches the gate chooses *by itself*
    (``.venv``, ``sys.executable``) — that is where the forged-symlink attack
    lives. An explicit ``OMNIAGENTOS_PYTHON`` is the operator deliberately
    naming an interpreter, which documented policy already treats as trusted;
    it is still forced to be a real virtualenv carrying the gate's tooling, so
    the override is strictly harder to abuse than before, not a bypass.
    """
    probe = probe_interpreter(python, timeout=timeout)

    if not probe.in_virtualenv:
        raise InterpreterError(
            f"refusing certification: {python!r} is not a virtualenv "
            f"(sys.prefix == sys.base_prefix == {probe.base_prefix!r}); "
            f"a resolved venv symlink collapses to the base interpreter"
        )

    if require_local_prefix and not _is_project_venv_prefix(Path(probe.prefix), repo_root):
        raise InterpreterError(
            f"refusing certification: {python!r} reports sys.prefix="
            f"{probe.prefix!r}, which is outside the repository {str(repo_root)!r}; "
            f"the gate must certify under the project's own environment"
        )

    missing = sorted(m for m, ok in probe.importable.items() if not ok)
    if missing:
        raise InterpreterError(
            f"refusing certification: {python!r} cannot import {', '.join(missing)}; "
            f"the interpreter cannot run the gate's own phases"
        )

    return probe


def default_phase_specs(*, python: str, repo_root: Path) -> tuple[PhaseSpec, ...]:
    """Canonical phase table for the immutable full gate.

    Commands are the intended release payloads. Satellite lanes own OpenAPI
    generation, dependency upgrades, coverage policy, and scale fixtures; the
    gate still names those phases so the orchestration cannot silently drop
    them.
    """
    py = python
    dash = str(repo_root / "dashboard")
    # pytest exits 0 when every selected test skips, and when a marker expression
    # deselects everything, so a phase that ran nothing still records "passed".
    # Every pytest phase therefore loads the no-silent-skip plugin; they differ
    # only in how much skipping is legitimate.
    #
    # A phase whose whole selection is one required payload tolerates no skip at
    # all. The whole-suite backend phase does have real optional skips (live
    # providers, extras) — but tolerating *some* skips is not a reason to
    # tolerate *all* of them, so it still refuses a session that executed zero
    # tests, which is what a broken conftest or a mis-set environment produces.
    strict = ("-p", NO_SILENT_SKIP_PLUGIN, "--no-silent-skip-mode", "required")
    nonempty = ("-p", NO_SILENT_SKIP_PLUGIN, "--no-silent-skip-mode", "nonempty")
    return (
        PhaseSpec(
            name="backend",
            description="Full backend pytest suite (not curated certification subset)",
            argv=(py, "-m", "pytest", "-q", *nonempty),
        ),
        PhaseSpec(
            name="dashboard_unit",
            description="Dashboard unit tests (vitest)",
            argv=("npm", "--prefix", dash, "test"),
        ),
        PhaseSpec(
            name="dashboard_lint",
            description="Dashboard ESLint",
            argv=("npm", "--prefix", dash, "run", "lint"),
        ),
        PhaseSpec(
            name="dashboard_build",
            description="Dashboard production build into isolated distDir",
            argv=("npm", "--prefix", dash, "run", "build"),
        ),
        PhaseSpec(
            name="e2e",
            description="Official cross-process E2E smoke",
            argv=("bash", str(repo_root / "scripts" / "smoke" / "e2e.sh")),
        ),
        PhaseSpec(
            name="ruff",
            description="Ruff lint",
            argv=(py, "-m", "ruff", "check", "."),
        ),
        PhaseSpec(
            name="format",
            description="Ruff format check (no rewrite)",
            argv=(py, "-m", "ruff", "format", "--check", "."),
        ),
        PhaseSpec(
            name="mypy",
            description="mypy type check of omniagentos package",
            argv=(py, "-m", "mypy", "omniagentos"),
        ),
        PhaseSpec(
            name="migrations",
            description="Apply/verify migrations against the gate DB",
            argv=(py, "-m", "omniagentos.db.migrate"),
        ),
        PhaseSpec(
            name="api_contracts",
            description=(
                f"Whole-API OpenAPI contract: {API_CONTRACT_ARTIFACT} presence + drift "
                f"(S19A-owned payload; regenerate with {API_CONTRACT_GENERATOR})"
            ),
            argv=(py, "-m", "pytest", "-q", *strict, API_CONTRACT_TEST),
        ),
        PhaseSpec(
            name="dependency_scan",
            description="Dashboard production dependency advisory scan",
            argv=("npm", "--prefix", dash, "audit", "--omit=dev", "--audit-level=high"),
        ),
        PhaseSpec(
            name="live_restart",
            description=(
                f"Selected live/restart path tests (S19B-owned payload, "
                f"marked {LIVE_RESTART_PAYLOAD_MARKER})"
            ),
            argv=(py, "-m", "pytest", "-q", *strict, "-m", LIVE_RESTART_SELECTION, "tests"),
            conditional=True,
            enable_env="RELEASE_GATE_LIVE",
        ),
        PhaseSpec(
            name="load_contention",
            description=(
                f"Bounded scale/backpressure and contention exits (S19B-owned "
                f"payload, marked {LOAD_CONTENTION_PAYLOAD_MARKER})"
            ),
            argv=(py, "-m", "pytest", "-q", *strict, "-m", LOAD_CONTENTION_SELECTION, "tests"),
            conditional=True,
            enable_env="RELEASE_GATE_LOAD",
        ),
    )


def _northstar_phase_specs(*, tier: str, repo_root: Path) -> tuple[PhaseSpec, ...]:
    """Return the additive North Star tier profile without changing H-30 defaults."""
    if tier not in NORTHSTAR_PHASE_SET_NAMES:
        raise ReleaseGateError(f"unknown North Star tier: {tier!r}")
    target = f"nscert-{tier}"
    return (
        PhaseSpec(
            name=f"northstar_{tier}",
            description=f"North Star {tier.upper()} manifest-selected certification",
            argv=("make", "-C", str(repo_root), target),
        ),
    )


def git_rev_parse_head(repo_root: Path, *, runner: CommandRunner | None = None) -> str:
    """Return the full HEAD sha."""
    code, out = _run_git(["rev-parse", "HEAD"], repo_root, runner=runner)
    if code != 0:
        raise ReleaseGateError(f"git rev-parse HEAD failed (rc={code}): {out.strip()}")
    sha = out.strip()
    if len(sha) < 7:
        raise ReleaseGateError(f"git rev-parse HEAD returned unusable sha: {sha!r}")
    return sha


def git_is_dirty(repo_root: Path, *, runner: CommandRunner | None = None) -> bool:
    """True when the worktree has uncommitted or untracked changes."""
    code, out = _run_git(["status", "--porcelain"], repo_root, runner=runner)
    if code != 0:
        raise ReleaseGateError(f"git status --porcelain failed (rc={code}): {out.strip()}")
    return bool(out.strip())


def git_dirty_summary(repo_root: Path, *, runner: CommandRunner | None = None) -> str:
    """Short porcelain summary for refuse messages (capped)."""
    code, out = _run_git(["status", "--porcelain"], repo_root, runner=runner)
    if code != 0:
        return f"(git status failed rc={code})"
    lines = [ln for ln in out.splitlines() if ln.strip()]
    if not lines:
        return ""
    head = lines[:12]
    extra = len(lines) - len(head)
    body = "\n".join(head)
    if extra > 0:
        body += f"\n... and {extra} more"
    return body


def _run_git(
    args: Sequence[str],
    repo_root: Path,
    *,
    runner: CommandRunner | None = None,
) -> tuple[int, str]:
    argv = ["git", "-C", str(repo_root), *args]
    if runner is not None:
        return runner(argv, repo_root)
    return _default_runner(argv, repo_root)


def _default_runner(
    argv: Sequence[str],
    cwd: Path,
    env: Mapping[str, str] | None = None,
) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            list(argv),
            cwd=str(cwd),
            capture_output=True,
            text=True,
            check=False,
            env=dict(env) if env is not None else None,
        )
    except FileNotFoundError as exc:
        return 127, f"command not found: {argv[0]} ({exc})"
    combined = (proc.stdout or "") + (proc.stderr or "")
    return int(proc.returncode), combined


def make_default_runner(env: Mapping[str, str] | None = None) -> CommandRunner:
    """Bind *env* to the default subprocess runner.

    Keeps the two-argument :data:`CommandRunner` contract that injected test
    runners rely on while letting the gate hand certification environment
    (notably ``OMNIAGENTOS_REQUIRE_PG=1``) to every phase subprocess.
    """
    bound = dict(env) if env is not None else None

    def _runner(argv: Sequence[str], cwd: Path) -> tuple[int, str]:
        return _default_runner(argv, cwd, env=bound)

    return _runner


def assert_clean_and_pinned(
    repo_root: Path,
    pinned_sha: str,
    *,
    allow_dirty: bool = False,
    runner: CommandRunner | None = None,
) -> str:
    """Refuse dirty or moved HEAD. Returns the verified current HEAD sha."""
    head = git_rev_parse_head(repo_root, runner=runner)
    if head != pinned_sha:
        raise MovingHeadError(f"HEAD moved during release gate: pinned={pinned_sha} current={head}")
    if not allow_dirty and git_is_dirty(repo_root, runner=runner):
        summary = git_dirty_summary(repo_root, runner=runner)
        raise DirtyTreeError(
            "worktree is dirty — release gate refuses certification on a "
            f"moving/dirty tree at {pinned_sha}:\n{summary}"
        )
    return head


def select_phases(
    specs: Sequence[PhaseSpec],
    *,
    only: Sequence[str] | None = None,
    env: Mapping[str, str] | None = None,  # noqa: ARG001 (kept for API symmetry)
) -> list[PhaseSpec]:
    """Filter phase specs by name list (None = all) and conditional env flags.

    Conditional phases default to *enabled* when their env var is unset so the
    full gate includes them. Set ``RELEASE_GATE_LIVE=0`` / ``RELEASE_GATE_LOAD=0``
    to skip with explicit evidence (not a silent drop from the plan).

    Note: The *env* parameter is accepted for API symmetry with phase_should_run
    but phase selection itself does not depend on environment variables.
    """
    wanted: set[str] | None
    if only is None:
        wanted = None
    else:
        wanted = {n.strip() for n in only if n.strip()}
        unknown = wanted - {s.name for s in specs}
        if unknown:
            raise ReleaseGateError(f"unknown phase name(s): {sorted(unknown)}")

    selected: list[PhaseSpec] = []
    for spec in specs:
        if wanted is not None and spec.name not in wanted:
            continue
        selected.append(spec)
    # Preserve canonical order
    order = {name: i for i, name in enumerate(ALL_PHASE_NAMES)}
    selected.sort(key=lambda s: order.get(s.name, 999))
    return selected


def phase_should_run(spec: PhaseSpec, env: Mapping[str, str] | None = None) -> bool:
    """Whether a (possibly conditional) phase should execute."""
    if not spec.conditional:
        return True
    e = env if env is not None else os.environ
    key = spec.enable_env or ""
    if not key:
        return True
    raw = e.get(key)
    if raw is None:
        # Default ON for full-gate certification.
        return True
    return _truthy(raw)


def run_phase(
    spec: PhaseSpec,
    *,
    repo_root: Path,
    pinned_sha: str,
    allow_dirty: bool,
    dry_run: bool = False,
    env: Mapping[str, str] | None = None,
    runner: CommandRunner | None = None,
) -> PhaseEvidence:
    """Execute one phase under pinned-SHA / clean-tree enforcement."""
    started = _utc_now()
    t0 = time.monotonic()
    head_start = assert_clean_and_pinned(
        repo_root, pinned_sha, allow_dirty=allow_dirty, runner=runner
    )

    if dry_run:
        ended = _utc_now()
        return PhaseEvidence(
            name=spec.name,
            status="planned",
            pinned_sha=pinned_sha,
            head_sha_at_start=head_start,
            head_sha_at_end=head_start,
            started_at=started,
            ended_at=ended,
            duration_ms=int((time.monotonic() - t0) * 1000),
            exit_code=None,
            command=list(spec.argv),
            detail=spec.description,
        )

    if not phase_should_run(spec, env=env):
        ended = _utc_now()
        head_end = assert_clean_and_pinned(
            repo_root, pinned_sha, allow_dirty=allow_dirty, runner=runner
        )
        return PhaseEvidence(
            name=spec.name,
            status="skipped",
            pinned_sha=pinned_sha,
            head_sha_at_start=head_start,
            head_sha_at_end=head_end,
            started_at=started,
            ended_at=ended,
            duration_ms=int((time.monotonic() - t0) * 1000),
            exit_code=None,
            command=list(spec.argv),
            detail=(f"conditional phase disabled via {spec.enable_env}=0 ({spec.description})"),
        )

    # With no injected runner this is the layer that actually spawns the phase,
    # so this is where the certification environment must be applied — a caller
    # invoking run_phase directly must not get a subprocess that can skip its
    # PostgreSQL-backed tests into a false green.
    run = runner or make_default_runner(certification_env(env))
    code, output = run(spec.argv, repo_root)
    # Re-pin check after the phase — refuse if HEAD moved during the phase.
    try:
        head_end = assert_clean_and_pinned(
            repo_root, pinned_sha, allow_dirty=allow_dirty, runner=runner
        )
    except ReleaseGateError as exc:
        ended = _utc_now()
        return PhaseEvidence(
            name=spec.name,
            status="refused",
            pinned_sha=pinned_sha,
            head_sha_at_start=head_start,
            head_sha_at_end="",
            started_at=started,
            ended_at=ended,
            duration_ms=int((time.monotonic() - t0) * 1000),
            exit_code=code,
            command=list(spec.argv),
            detail=str(exc),
            log_excerpt=_excerpt(output),
        )

    ended = _utc_now()
    status: PhaseStatus = "passed" if code == 0 else "failed"
    return PhaseEvidence(
        name=spec.name,
        status=status,
        pinned_sha=pinned_sha,
        head_sha_at_start=head_start,
        head_sha_at_end=head_end,
        started_at=started,
        ended_at=ended,
        duration_ms=int((time.monotonic() - t0) * 1000),
        exit_code=code,
        command=list(spec.argv),
        detail=spec.description if code == 0 else f"phase failed with exit {code}",
        log_excerpt=_excerpt(output),
    )


def _excerpt(text: str, limit: int = 4000) -> str:
    text = text or ""
    if len(text) <= limit:
        return text
    return text[: limit - 20] + "\n...[truncated]..."


def write_evidence(evidence: GateEvidence, path: Path) -> Path:
    """Persist gate evidence as JSON, refusing to overwrite an existing record.

    Opened ``O_CREAT | O_EXCL`` rather than checked-then-written: two concurrent
    gate runs that generated the same candidate name would both pass an
    ``exists()`` test and the second would silently overwrite the first's audit
    trail. Exclusive creation makes the loser fail instead of destroying
    evidence, which is the whole point of the record.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(evidence.to_dict(), indent=2, sort_keys=True) + "\n"
    fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(payload)
    return path


def _evidence_stamp() -> str:
    """UTC stamp for evidence filenames (microsecond resolution)."""
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")


def evidence_path_for(
    repo_root: Path, pinned_sha: str, env: Mapping[str, str] | None = None
) -> Path:
    """Default evidence location under the lane/runtime var dir.

    The filename must be unique even when two gate runs share a pinned SHA
    *and* start within the same clock tick — a second-resolution
    ``<stamp>-<sha>.json`` name silently overwrote the earlier run's evidence,
    destroying exactly the audit trail the gate exists to produce. Uniqueness
    comes from four independent sources: microsecond stamp, an in-process
    monotonic sequence, the pid (distinguishes concurrent processes), and a
    random suffix (survives pid reuse).

    This returns a *candidate*; it deliberately does not probe the filesystem,
    because a check here could not bind the later write anyway. Exclusivity is
    enforced where it is actually atomic, by :func:`write_evidence`.
    """
    e = env if env is not None else os.environ
    var = (e.get("OMNIAGENTOS_VAR_DIR") or e.get("OMNIAGENTOS_VAR") or "").strip()
    base = Path(var) if var else (repo_root / "var")
    short = pinned_sha[:12] if pinned_sha else "unknown"
    stamp = _evidence_stamp()
    seq = next(_EVIDENCE_SEQ)
    suffix = uuid.uuid4().hex[:8]
    return base / "release-gate" / f"{stamp}-{short}-p{os.getpid()}-s{seq}-{suffix}.json"


def certification_env(base: Mapping[str, str] | None = None) -> dict[str, str]:
    """Environment handed to phase subprocesses during certification."""
    env = dict(base if base is not None else os.environ)
    env[ENV_REQUIRE_PG] = "1"
    env.pop("PYTEST_ADDOPTS", None)
    return env


def run_release_gate(
    *,
    repo_root: Path | None = None,
    phases: Sequence[str] | None = None,
    dry_run: bool = False,
    allow_dirty: bool | None = None,
    env: Mapping[str, str] | None = None,
    runner: CommandRunner | None = None,
    evidence_path: Path | None = None,
    stop_on_failure: bool = True,
    python: str | None = None,
    verify_interpreter: bool = True,
) -> GateEvidence:
    """Run the immutable pinned-SHA release gate.

    Returns :class:`GateEvidence` for every outcome including refusals. Raises
    only for programmer errors (unknown phase names before pin). Dirty/moved
    HEAD become ``status="refused"`` evidence rather than uncaught exceptions
    at this layer so callers always get a durable record.
    """
    e = dict(env) if env is not None else dict(os.environ)
    root = (repo_root or default_repo_root()).resolve()
    if allow_dirty is None:
        allow_dirty = _truthy(e.get("RELEASE_GATE_ALLOW_DIRTY"))

    started = _utc_now()

    # Refuse certification if PYTEST_ADDOPTS is present in environment
    if (e.get("PYTEST_ADDOPTS") or "").strip():
        evidence = GateEvidence(
            pinned_sha="",
            status="refused",
            started_at=started,
            ended_at=_utc_now(),
            repo_root=str(root),
            allow_dirty=bool(allow_dirty),
            refuse_reason=(
                f"refusing certification: PYTEST_ADDOPTS={e['PYTEST_ADDOPTS']!r} is set in environment; "
                "pytest addopts poisoning can silently alter or deselect gate test suites"
            ),
            selected_phases=list(phases or []),
            interpreter_verified=False,
        )
        _maybe_write(evidence, evidence_path, root, e)
        return evidence

    # Resolve the audited project interpreter; refuse certification if not local.
    # Resolution is a path-shape check only, so the selected interpreter is then
    # *executed* and made to prove it is the project venv and can import the
    # gate's tooling. Skipped when a runner is injected: those callers replace
    # the whole subprocess world, so there is no real interpreter to interrogate.
    # A run that skipped verification is recorded as such and can never end in
    # ``passed`` — otherwise these two carve-outs would emit evidence identical
    # to a real certification, and the check would be optional in practice.
    #
    # ``interpreter_verified`` records what *happened*, not what was intended, so
    # it starts False and is set only once verification has actually returned. A
    # run that intended to verify but was refused by the check did not verify,
    # and its evidence must not claim otherwise.
    will_verify = runner is None and verify_interpreter
    interpreter_verified = False
    try:
        py = python or resolve_python(e, repo_root=root, require_project_local=True)
        if will_verify:
            verify_certification_interpreter(py, repo_root=root, require_local_prefix=True)
            interpreter_verified = True
    except InterpreterError as exc:
        evidence = GateEvidence(
            pinned_sha="",
            status="refused",
            started_at=started,
            ended_at=_utc_now(),
            repo_root=str(root),
            allow_dirty=bool(allow_dirty),
            refuse_reason=str(exc),
            selected_phases=list(phases or []),
            interpreter_verified=interpreter_verified,
        )
        _maybe_write(evidence, evidence_path, root, e)
        return evidence

    # Phase subprocesses run under the certification environment (REQUIRE_PG=1)
    # so PG-backed tests fail loudly instead of skipping into a false green.
    # run_phase applies it; an injected runner (tests) owns its own world.
    specs = default_phase_specs(python=py, repo_root=root)

    try:
        selected = select_phases(specs, only=phases, env=e)
    except ReleaseGateError as exc:
        evidence = GateEvidence(
            pinned_sha="",
            status="refused",
            started_at=started,
            ended_at=_utc_now(),
            repo_root=str(root),
            allow_dirty=bool(allow_dirty),
            refuse_reason=str(exc),
            selected_phases=list(phases or []),
            python=py,
            require_pg=True,
            interpreter_verified=interpreter_verified,
        )
        _maybe_write(evidence, evidence_path, root, e)
        return evidence

    # --- pin once ---------------------------------------------------------
    try:
        pinned_sha = git_rev_parse_head(root, runner=runner)
        assert_clean_and_pinned(root, pinned_sha, allow_dirty=bool(allow_dirty), runner=runner)
    except ReleaseGateError as exc:
        # Best-effort pin for the record even on dirty refuse.
        try:
            pinned_sha = git_rev_parse_head(root, runner=runner)
        except ReleaseGateError:
            pinned_sha = ""
        evidence = GateEvidence(
            pinned_sha=pinned_sha,
            status="refused",
            started_at=started,
            ended_at=_utc_now(),
            repo_root=str(root),
            allow_dirty=bool(allow_dirty),
            refuse_reason=str(exc),
            selected_phases=[s.name for s in selected],
            python=py,
            require_pg=True,
            interpreter_verified=interpreter_verified,
        )
        _maybe_write(evidence, evidence_path, root, e)
        return evidence

    evidence = GateEvidence(
        pinned_sha=pinned_sha,
        status="planned" if dry_run else "passed",
        started_at=started,
        repo_root=str(root),
        allow_dirty=bool(allow_dirty),
        selected_phases=[s.name for s in selected],
        python=py,
        require_pg=True,
        interpreter_verified=interpreter_verified,
    )

    for spec in selected:
        try:
            phase_ev = run_phase(
                spec,
                repo_root=root,
                pinned_sha=pinned_sha,
                allow_dirty=bool(allow_dirty),
                dry_run=dry_run,
                env=e,
                runner=runner,
            )
        except ReleaseGateError as exc:
            phase_ev = PhaseEvidence(
                name=spec.name,
                status="refused",
                pinned_sha=pinned_sha,
                head_sha_at_start=pinned_sha,
                head_sha_at_end="",
                started_at=_utc_now(),
                ended_at=_utc_now(),
                duration_ms=0,
                exit_code=None,
                command=list(spec.argv),
                detail=str(exc),
            )
        evidence.phases.append(phase_ev)

        if phase_ev.status == "refused":
            evidence.status = "refused"
            evidence.refuse_reason = phase_ev.detail
            break
        if phase_ev.status == "failed":
            evidence.status = "failed"
            if stop_on_failure:
                break

    # Final provenance check when we still claim a non-refused outcome.
    if evidence.status in {"passed", "planned", "failed"}:
        try:
            assert_clean_and_pinned(root, pinned_sha, allow_dirty=bool(allow_dirty), runner=runner)
        except ReleaseGateError as exc:
            evidence.status = "refused"
            evidence.refuse_reason = str(exc)

    # Dry-run stays planned only if nothing refused.
    if dry_run and evidence.status == "passed":
        evidence.status = "planned"

    # Full-gate green requires every selected non-skipped phase to pass, and
    # no skipped conditional phases when running the complete plan without an
    # explicit phase filter. Skips are recorded honestly; they do not count as
    # a certified full gate.
    if (
        not dry_run
        and evidence.status == "passed"
        and phases is None
        and any(p.status == "skipped" for p in evidence.phases)
    ):
        evidence.status = "failed"
        evidence.refuse_reason = (
            "full gate incomplete: one or more conditional phases were skipped; "
            "set RELEASE_GATE_LIVE=1 and RELEASE_GATE_LOAD=1 for certification"
        )

    # Last word: only a verified interpreter may produce a certification. An
    # injected runner never executed the real commands and an unverified one may
    # not be the audited environment, so neither has certified anything — and
    # evidence saying "passed" is exactly how that would go unnoticed. Applied
    # after every other transition so no later rule can reinstate ``passed``.
    # Failures and refusals keep their own status: a simulated failure is still
    # a failure, and softening it here would be the same defect inverted.
    if evidence.status == "passed" and not interpreter_verified:
        evidence.status = "simulated"
        evidence.refuse_reason = (
            "not a certification: the interpreter was not verified "
            "(injected runner or verification disabled)"
        )

    # Dirty-mode override check: RELEASE_GATE_ALLOW_DIRTY=1 allows local debugging, but can NEVER certify or return exit 0.
    if evidence.allow_dirty and evidence.status in {"passed", "planned"}:
        evidence.status = "simulated"
        evidence.refuse_reason = (
            "not a certification: RELEASE_GATE_ALLOW_DIRTY=1 was used on a dirty tree"
        )

    evidence.ended_at = _utc_now()
    _maybe_write(evidence, evidence_path, root, e)
    return evidence


def _write_or_refuse(evidence: GateEvidence, path: Path) -> None:
    """Write the record, translating an unusable location into a refusal.

    ``FileExistsError`` is deliberately *not* translated: it is the collision
    signal :func:`_maybe_write` acts on, and for an operator-named path it is
    the verdict itself. Every other ``OSError`` becomes an
    :class:`EvidenceWriteError` so the caller can report an evidence problem as
    such, rather than labelling any stray I/O failure that way.
    """
    try:
        write_evidence(evidence, path)
    except FileExistsError:
        raise
    except OSError as exc:
        raise EvidenceWriteError(f"cannot write evidence to {path}: {exc}") from exc


def _maybe_write(
    evidence: GateEvidence,
    evidence_path: Path | None,
    root: Path,
    env: Mapping[str, str],
) -> None:
    """Persist the record, retrying only names the gate generated itself.

    An operator-supplied ``--evidence`` path is written exactly once: silently
    picking a different filename because theirs already existed would hide the
    clobber it is meant to prevent. Auto-generated names may be regenerated,
    since a collision there is a naming accident rather than an instruction.
    """
    if evidence_path is not None:
        _write_or_refuse(evidence, evidence_path)
        return

    sha = evidence.pinned_sha or "refused"
    last: OSError | None = None
    for _ in range(_EVIDENCE_WRITE_ATTEMPTS):
        try:
            _write_or_refuse(evidence, evidence_path_for(root, sha, env))
            return
        except FileExistsError as exc:  # regenerate and try a fresh name
            last = exc
    raise EvidenceWriteError(
        f"could not create a unique evidence file after {_EVIDENCE_WRITE_ATTEMPTS} attempts: {last}"
    )


def format_summary(evidence: GateEvidence) -> str:
    """Human-readable one-screen summary."""
    lines = [
        "════════════════════════════════════════════════════════════",
        " OmniAgentOS release gate (H-30)",
        f" status:     {evidence.status}",
        f" pinned_sha: {evidence.pinned_sha or '(none)'}",
        f" repo:       {evidence.repo_root}",
        f" python:     {evidence.python or '(unresolved)'}",
        f" require_pg: {'1' if evidence.require_pg else '0'}",
        f" started:    {evidence.started_at}",
        f" ended:      {evidence.ended_at}",
    ]
    if evidence.allow_dirty:
        lines.append(" WARNING:    RELEASE_GATE_ALLOW_DIRTY=1 (not certifiable)")
    if evidence.refuse_reason:
        lines.append(f" refuse:     {evidence.refuse_reason}")
    lines.append(" phases:")
    if not evidence.phases:
        lines.append("   (none executed)")
    for p in evidence.phases:
        rc = "-" if p.exit_code is None else str(p.exit_code)
        lines.append(f"   [{p.status:8}] {p.name:18} rc={rc:4} {p.duration_ms}ms")
    lines.append("════════════════════════════════════════════════════════════")
    return "\n".join(lines)


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="omniagentos.harnesses.release_gate",
        description="Immutable pinned-SHA release / convergence gate (H-30).",
    )
    p.add_argument(
        "--list",
        action="store_true",
        help="List named phases and exit without running them.",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Pin SHA, enforce clean tree, plan phases without executing them.",
    )
    p.add_argument(
        "--phases",
        default="",
        help="Comma-separated subset of phases (default: full gate).",
    )
    p.add_argument(
        "--repo-root",
        default="",
        help="Repository root (default: auto-detect).",
    )
    p.add_argument(
        "--evidence",
        default="",
        help="Path for evidence JSON (default: $OMNIAGENTOS_VAR_DIR/release-gate/).",
    )
    p.add_argument(
        "--allow-dirty",
        action="store_true",
        help="Debug only: allow dirty tree (evidence records the override).",
    )
    p.add_argument(
        "--continue-on-failure",
        action="store_true",
        help="Run remaining phases after a failure (default: stop on first fail).",
    )
    return p


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(list(argv) if argv is not None else None)
    root = Path(args.repo_root).resolve() if args.repo_root else default_repo_root()

    # --list is informational only; does not require a certified interpreter.
    if args.list:
        try:
            py = resolve_python(repo_root=root, require_project_local=False)
        except InterpreterError:
            py = "python"  # fallback for display only
        specs = default_phase_specs(python=py, repo_root=root)
        for spec in specs:
            flag = " (conditional)" if spec.conditional else ""
            print(f"{spec.name:18}  {spec.description}{flag}")
        return 0

    only = [x.strip() for x in args.phases.split(",") if x.strip()] or None
    allow_dirty = bool(args.allow_dirty) or _truthy(os.environ.get("RELEASE_GATE_ALLOW_DIRTY"))
    # Interpreter resolution happens inside run_release_gate with proper validation.
    try:
        evidence = run_release_gate(
            repo_root=root,
            phases=only,
            dry_run=bool(args.dry_run),
            allow_dirty=allow_dirty,
            evidence_path=Path(args.evidence) if args.evidence else None,
            stop_on_failure=not bool(args.continue_on_failure),
        )
    except (EvidenceWriteError, FileExistsError) as exc:
        # An unrecordable verdict must refuse with a legible reason, not abort
        # with a traceback: the verdict is worthless unrecorded, and a crash
        # here is indistinguishable from a crashed gate. Only evidence errors
        # are caught — a stray I/O failure elsewhere must not be reported as
        # an evidence problem.
        print(f"release gate refused: cannot record evidence — {exc}", file=sys.stderr)
        return 3
    print(format_summary(evidence))
    if evidence.status in {"passed", "planned"}:
        return 0
    if evidence.status == "refused":
        return 3
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
