"use client";
import { useCallback, useEffect, useState } from "react";
import { Badge, Button, StatusDot } from "../design";
import { api } from "../lib/api";
import { startVisibilityPoll } from "../lib/pollWhenVisible";
import type { PauseState } from "../lib/contracts";
// Always-on (mounted by app/layout.tsx on every page): rides the ONE shared
// per-tab EventSource instead of opening its own (T1.4). Same return shape as
// the frozen useEvents.
import { useEventChannel } from "../lib/useEventChannel";
export function PauseControl() { const [paused, setPaused] = useState(false); const [reason, setReason] = useState(""); const [updatedAt, setUpdatedAt] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const { lastEvent } = useEventChannel(["pause.changed"]); const apply = useCallback((state: PauseState) => { setPaused(!!state.paused); setReason(state.reason ?? ""); setUpdatedAt(state.updated_at ?? null); setError(null); }, []); const refresh = useCallback(async () => { try { apply(await api.pause()); } catch (err) { setError(err instanceof Error ? err.message : "Failed to load pause state"); } }, [apply]); useEffect(() => { void refresh(); return startVisibilityPoll(() => void refresh(), 30_000); }, [refresh]); useEffect(() => { const payload = lastEvent?.payload ?? {}; if (lastEvent?.type === "pause.changed" && typeof payload.paused === "boolean") { setPaused(payload.paused); setReason(typeof payload.reason === "string" ? payload.reason : ""); setUpdatedAt(lastEvent.ts); } }, [lastEvent]); const set = async (value: boolean) => { setBusy(true); setError(null); try { apply(await api.setPause(value, value ? "Operator pause" : "")); } catch (err) { setError(err instanceof Error ? err.message : "Failed to update pause state"); } finally { setBusy(false); } }; return <div role="alert" aria-live="assertive" className="ds-inline-row"><StatusDot state={paused ? "paused" : "ok"} /><Badge tone={paused ? "paused" : "ok"}>{paused ? `Paused${reason ? ` — ${reason}` : ""}` : "Running"}</Badge>{updatedAt ? <span>since {new Date(updatedAt).toLocaleTimeString()}</span> : null}<Button variant={paused ? "primary" : "danger"} size="sm" onClick={() => void set(!paused)} disabled={busy}>{busy ? "Working…" : paused ? "Resume" : "Pause"}</Button>{error ? <span role="status">{error}</span> : null}</div>; }
