"""Export verified skill bodies from the database to versioned repo files.

The DB skill library only ever reaches agent briefs on the box that owns the
database (`resolve.py` reads `skill_versions.content_snapshot` at spawn time).
This module is the distribution bridge: it writes each servable skill to
``<out_dir>/<slug>/SKILL.md`` so approved skills travel to the rest of the team
through git, and `scripts/team/skills_sync.py` installs them per machine.

Three rules make an exported file trustworthy:

1. **The resolver decides what is servable.** Verification is not
   re-implemented here — every candidate goes through
   :func:`omniagentos.skills.resolve.resolve_approved_skill_content`, the ONE
   approved content path, which re-reads the row, re-checks the status against
   the selectable vocabulary and recomputes the content digest. A skill the
   resolver drops is never written; this module only *labels* the failure for
   the report (see :func:`_classify_drop`).

2. **Every body is re-scanned before it leaves the box.** ``upsert_skill``
   scans content only when a skill is INSERTED; its UPDATE path rewrites
   ``content_snapshot`` and recomputes the digest without rescanning. So a
   row can hold dangerous content, a valid digest and ``status='active'`` all
   at once — which the resolver would happily serve. Export is a wider blast
   radius than a local brief (the file lands in git and is copied onto three
   laptops), so :func:`omniagentos.skills.scan.scan_content` runs again here
   and a flagged skill is dropped, never exported.

3. **The output is byte-deterministic.** ``exported_at`` is the SELECTED
   VERSION's own ``created_at``, never ``now()`` — and deliberately not
   ``skills.updated_at``, which the startup vault re-index rewrites on every
   run and which would therefore produce a whole-corpus diff on every export.
   Re-exporting an unchanged corpus writes byte-identical files, so a diff in
   ``skills-lib/`` means a skill actually changed.

There is NO ``approved`` status in this schema. Migration 109 fixed the
vocabulary at ``active | archived | quarantined | deprecated | experimental``
and dropped ``approved``/``canary`` from the selector because nothing can
produce them; :data:`EXPORTABLE_STATUSES` is exactly the subset the resolver
will serve.

CLI: ``python -m omniagentos.skills export --out skills-lib/``.
"""

from __future__ import annotations

import json
import logging
import re
import shutil
import sqlite3
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from omniagentos.contracts import default_db_path, digest
from omniagentos.db.migrate import migrate_connection
from omniagentos.db.store import _connect
from omniagentos.skills.resolve import (
    DROP_DIGEST_MISMATCH,
    DROP_EMPTY_CONTENT,
    DROP_MISSING_DIGEST,
    resolve_approved_skill_content,
)
from omniagentos.skills.scan import scan_content
from omniagentos.skills.select import _STATUS_MATCHABLE, SkillHit

LOG = logging.getLogger(__name__)

# The statuses the resolver will actually serve, so the export cannot ship a
# body that would be dropped at read time. Kept derived from select.py's set
# rather than re-typed, so widening the vocabulary in one place widens it here.
EXPORTABLE_STATUSES: tuple[str, ...] = tuple(sorted(_STATUS_MATCHABLE))

# Drop reasons this module adds on top of resolve.py's. Distinguishable on
# purpose: "the scanner flagged the body" is not "someone edited it under us".
DROP_SCANNER_FLAGGED = "scanner_flagged"
DROP_UNVERIFIED = "unverified"
DROP_UNSAFE_SLUG = "unsafe_slug"

# A slug becomes a literal directory name under the export destination, and the
# DB schema does not constrain slugs — a row written around the DAL must still
# never become a path. Single safe segment only: no separators, no leading dot.
_SAFE_SLUG = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}")

SKILL_FILENAME = "SKILL.md"


class ExportPathError(RuntimeError):
    """A skill would have written outside its export directory."""


# Frontmatter key order is fixed (it is part of the byte-determinism contract).
_FRONTMATTER_BANNER = (
    "# Generated by `python -m omniagentos.skills export` from the skill "
    "library database.\n# Do not hand-edit: the next export overwrites it. "
    "Edit the skill, then re-export.\n"
)


@dataclass(frozen=True, slots=True)
class ExportedSkill:
    """One skill written to disk, and whether this run changed its bytes."""

    slug: str
    version: int
    status: str
    content_digest: str
    path: Path
    changed: bool


@dataclass(frozen=True, slots=True)
class SkippedSkill:
    """A candidate that did not survive verification or the scanner, and why."""

    slug: str
    version: int
    reason: str
    detail: str = ""


@dataclass(frozen=True, slots=True)
class ExportReport:
    """What an export run did. ``skipped`` is never silently empty-by-default."""

    out_dir: Path
    exported: tuple[ExportedSkill, ...]
    skipped: tuple[SkippedSkill, ...]
    removed: tuple[str, ...]

    @property
    def changed_count(self) -> int:
        """Skills whose bytes this run added, rewrote or deleted."""
        return sum(1 for item in self.exported if item.changed) + len(self.removed)


def _candidate_rows(connection: sqlite3.Connection, statuses: Sequence[str]) -> list[sqlite3.Row]:
    """Every skill in *statuses*, joined to its SELECTED version, slug order.

    ``current_version`` is joined explicitly rather than taking whichever row
    carries ``status='active'`` — the same rule the resolver uses, so export
    and brief construction can never disagree about which body is current.
    """
    placeholders = ",".join("?" for _ in statuses)
    return list(
        connection.execute(
            "SELECT s.slug AS slug, s.category AS category, s.subcategory AS subcategory, "
            "s.title AS title, s.summary AS summary, s.status AS status, "
            "v.version AS version, v.content_snapshot AS content_snapshot, "
            "v.content_digest AS content_digest, v.created_at AS created_at "
            "FROM skills s JOIN skill_versions v "
            "  ON v.skill_id = s.id AND v.version = s.current_version "
            f"WHERE s.status IN ({placeholders}) "
            "ORDER BY s.slug",
            tuple(statuses),
        ).fetchall()
    )


def _classify_drop(content: str, recorded: object) -> tuple[str, str]:
    """Label a drop the resolver already made. It does NOT make the decision.

    The verdict belongs to ``resolve.py``; repeating the checks here would be a
    second implementation that could disagree with the first. This only asks
    "which of the resolver's documented reasons fits this row" so the report
    can say something more useful than "dropped". A row that looks fine and
    was still dropped is reported as :data:`DROP_UNVERIFIED` rather than being
    guessed into a specific cause.
    """
    if not content.strip():
        return DROP_EMPTY_CONTENT, "content is empty"
    if recorded is None or not str(recorded).strip():
        return DROP_MISSING_DIGEST, "no digest was recorded when this version was written"
    actual = digest(content)
    if actual != str(recorded):
        return DROP_DIGEST_MISMATCH, f"recorded={str(recorded)[:12]}… actual={actual[:12]}…"
    return DROP_UNVERIFIED, "the resolver did not return this skill; see its log for the fault"


def _yaml_scalar(value: object) -> str:
    """Render a frontmatter value as a YAML scalar.

    ``json.dumps`` emits a double-quoted string whose escapes (``\\n``, ``\\"``,
    ``\\\\``, ``\\uXXXX``) are all valid in YAML's double-quoted style, so this
    round-trips through ``yaml.safe_load`` without a YAML dumper's key
    reordering or line wrapping — both of which would cost byte-determinism.
    """
    if isinstance(value, bool):  # pragma: no cover - no boolean fields today
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps("" if value is None else str(value), ensure_ascii=False)


def _render(row: sqlite3.Row, content: str) -> str:
    """Render one ``SKILL.md``: fixed-order frontmatter plus the body snapshot."""
    fields: list[tuple[str, object]] = [
        ("slug", row["slug"]),
        ("category", row["category"]),
        ("subcategory", row["subcategory"]),
        ("title", row["title"]),
        ("summary", row["summary"]),
        ("status", row["status"]),
        ("version", int(row["version"])),
        ("content_digest", row["content_digest"]),
        # The version's own timestamp, never now(): see the module docstring.
        ("exported_at", row["created_at"]),
    ]
    lines = ["---", _FRONTMATTER_BANNER.rstrip("\n")]
    lines.extend(f"{name}: {_yaml_scalar(value)}" for name, value in fields)
    lines.append("---")
    body = content if content.endswith("\n") else content + "\n"
    return "\n".join(lines) + "\n" + body


def _write_if_changed(path: Path, text: str) -> bool:
    """Write *text* only when it differs. Returns True when bytes changed.

    Unchanged files are left untouched so a no-op export produces no mtime
    churn and no staged git change — that is what makes "export N changed
    skill(s)" a true statement rather than a count of everything.
    """
    payload = text.encode("utf-8")
    # A pre-existing symlink at <out_dir>/<slug> (or the file itself) would let
    # a validated slug still redirect the write outside the tree. Refuse it —
    # the exporter only ever writes plain dirs it created.
    if path.is_symlink() or path.parent.is_symlink():
        raise ExportPathError(f"refusing to write through a symlink: {path}")
    try:
        if path.read_bytes() == payload:
            return False
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return True


def _prune(out_dir: Path, keep: set[str]) -> tuple[str, ...]:
    """Remove previously exported skill dirs that this run did not write.

    Only directories this exporter could have created are touched: the child
    must contain a ``SKILL.md`` and NOTHING ELSE. A directory carrying extra
    files is somebody else's (a hand-written skill with scripts/references, a
    dev's stray notes) and is left alone with a warning rather than deleted.
    """
    removed: list[str] = []
    for child in sorted(out_dir.iterdir()):
        if not child.is_dir() or child.name in keep:
            continue
        names = {entry.name for entry in child.iterdir()}
        if names != {SKILL_FILENAME}:
            if SKILL_FILENAME in names:
                LOG.warning(
                    "skills export: leaving %s alone — it holds files this exporter "
                    "did not write (%s)",
                    child,
                    ", ".join(sorted(names - {SKILL_FILENAME})),
                )
            continue
        shutil.rmtree(child)
        removed.append(child.name)
    return tuple(removed)


def export_skills(
    out_dir: str | Path,
    statuses: Sequence[str] = EXPORTABLE_STATUSES,
    *,
    database: str | Path | None = None,
    prune: bool = True,
) -> ExportReport:
    """Export every servable skill to ``<out_dir>/<slug>/SKILL.md``.

    *statuses* must be a subset of :data:`EXPORTABLE_STATUSES` — asking for
    ``archived`` or ``quarantined`` is refused rather than quietly returning
    nothing, because the resolver would drop those bodies at read time and an
    export that ships them would be handing every dev a skill the orchestrator
    itself will not use.

    Skills that fail digest verification or the content scanner are DROPPED and
    reported in :attr:`ExportReport.skipped`; the export still succeeds with
    the rest. Nothing about a dropped skill is written to disk.
    """
    requested = tuple(dict.fromkeys(str(status).strip().lower() for status in statuses))
    if not requested:
        raise ValueError("statuses must name at least one status")
    unknown = [status for status in requested if status not in EXPORTABLE_STATUSES]
    if unknown:
        extra = ""
        if "approved" in unknown:
            extra = (
                " There is no 'approved' status in this schema: migration 109 fixed the "
                "vocabulary at active/archived/quarantined/deprecated/experimental and "
                "dropped approved/canary because nothing produces them."
            )
        raise ValueError(
            f"cannot export status(es) {sorted(unknown)}: the resolver only serves "
            f"{list(EXPORTABLE_STATUSES)}.{extra}"
        )

    destination = Path(out_dir)
    destination.mkdir(parents=True, exist_ok=True)
    db_path = str(database) if database is not None else default_db_path()

    connection = _connect(db_path)
    try:
        migrate_connection(connection)
        rows = _candidate_rows(connection, requested)
    finally:
        connection.close()

    # ONE call into the approved content path; it verifies status + digest and
    # records its own drops (log line, events row, process counter).
    hits = [
        SkillHit(name=str(row["slug"]), version=str(row["version"]), score=0.0, reason="export")
        for row in rows
    ]
    registry_rows = [{"name": str(row["slug"]), "title": str(row["title"] or "")} for row in rows]
    verified = {
        resolved.name: resolved
        for resolved in resolve_approved_skill_content(hits, registry_rows, database=db_path)
    }

    exported: list[ExportedSkill] = []
    skipped: list[SkippedSkill] = []
    for row in rows:
        slug = str(row["slug"])
        version = int(row["version"])
        if not _SAFE_SLUG.fullmatch(slug):
            detail = "slug is not a safe path segment"
            LOG.warning(
                "skills export: dropped %s@%s — %s: %s", slug, version, DROP_UNSAFE_SLUG, detail
            )
            skipped.append(SkippedSkill(slug, version, DROP_UNSAFE_SLUG, detail))
            continue
        resolved = verified.get(slug)
        if resolved is None:
            reason, detail = _classify_drop(
                str(row["content_snapshot"] or ""), row["content_digest"]
            )
            LOG.warning("skills export: dropped %s@%s — %s: %s", slug, version, reason, detail)
            skipped.append(SkippedSkill(slug, version, reason, detail))
            continue
        result = scan_content(resolved.content)
        if not result.passed:
            patterns = sorted({finding.pattern for finding in result.findings})
            detail = f"{result.summary} ({', '.join(patterns)})"
            LOG.warning(
                "skills export: dropped %s@%s — %s: %s",
                slug,
                version,
                DROP_SCANNER_FLAGGED,
                detail,
            )
            skipped.append(SkippedSkill(slug, version, DROP_SCANNER_FLAGGED, detail))
            continue
        path = destination / slug / SKILL_FILENAME
        changed = _write_if_changed(path, _render(row, resolved.content))
        exported.append(
            ExportedSkill(
                slug=slug,
                version=version,
                status=str(row["status"]),
                content_digest=resolved.content_digest,
                path=path,
                changed=changed,
            )
        )

    removed = _prune(destination, {item.slug for item in exported}) if prune else ()
    return ExportReport(
        out_dir=destination,
        exported=tuple(exported),
        skipped=tuple(skipped),
        removed=removed,
    )


__all__ = [
    "DROP_SCANNER_FLAGGED",
    "DROP_UNSAFE_SLUG",
    "DROP_UNVERIFIED",
    "EXPORTABLE_STATUSES",
    "SKILL_FILENAME",
    "ExportReport",
    "ExportedSkill",
    "SkippedSkill",
    "export_skills",
]
