#!/usr/bin/env python3
"""Generate the LiveSim test registry from the test files themselves.

The registry is the discoverable, machine-readable catalogue of every LiveSim
test: its id, category, type markers, live targets, one-line intent, and the
exact command to run it. It is generated by AST-parsing the test modules so it
can never drift from the actual tests (regenerate after adding/removing a test).

Actual results, expected/observed values, cost, latency, timestamps and full run
history live in the run ledger (var/livesim/ledger.jsonl + runs/<id>/*.json);
the registry points at them. Evidence (traces, dumps, UI reports) lives under
var/livesim/evidence/<run_id>/.

    scripts/livesim/gen_registry.py            # write configs/livesim-registry.yaml
    scripts/livesim/gen_registry.py --print    # print to stdout only
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import livesim_common as lc  # noqa: E402

CAT_DIR = lc.REPO / "tests" / "livesim" / "categories"
OUT = lc.REPO / "configs" / "livesim-registry.yaml"

TYPE_MARKERS = {
    "positive", "negative", "boundary", "concurrency", "recovery",
    "permission", "security", "degradation", "e2e_live",
}


def _marker_names(dec: ast.expr) -> list[str]:
    # @pytest.mark.<name> or @pytest.mark.<name>(...)
    node = dec.func if isinstance(dec, ast.Call) else dec
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    parts.reverse()
    if "mark" in parts:
        i = parts.index("mark")
        return parts[i + 1:]
    return []


def _targets_in_body(fn: ast.FunctionDef) -> list[str]:
    """Extract literal args of any livesim.target('api', 'db', ...) call."""
    out: list[str] = []
    for node in ast.walk(fn):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "target"
        ):
            for a in node.args:
                if isinstance(a, ast.Constant) and isinstance(a.value, str):
                    if a.value not in out:
                        out.append(a.value)
    return out


def _first_docline(fn: ast.FunctionDef) -> str:
    doc = ast.get_docstring(fn) or ""
    return doc.strip().splitlines()[0].strip() if doc.strip() else ""


def build() -> dict:
    entries = []
    counts = {"tests": 0, "by_category": {}, "by_type": {}}
    for path in sorted(CAT_DIR.glob("test_*.py")):
        category = path.stem.replace("test_", "")
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for fn in tree.body:
            if not isinstance(fn, ast.FunctionDef) or not fn.name.startswith("test_"):
                continue
            markers: list[str] = []
            for dec in fn.decorator_list:
                markers.extend(_marker_names(dec))
            types = sorted(m for m in markers if m in TYPE_MARKERS)
            targets = _targets_in_body(fn)
            nodeid = f"tests/livesim/categories/{path.name}::{fn.name}"
            entries.append(
                {
                    "id": f"{category}::{fn.name}",
                    "nodeid": nodeid,
                    "category": category,
                    "types": types or ["unclassified"],
                    "live_target": targets,
                    "summary": _first_docline(fn) or fn.name.replace("test_", "").replace("_", " "),
                    "command": (
                        f".venv/bin/python -m pytest {nodeid} -o addopts= -m livesim -q"
                    ),
                }
            )
            counts["tests"] += 1
            counts["by_category"][category] = counts["by_category"].get(category, 0) + 1
            for t in types:
                counts["by_type"][t] = counts["by_type"].get(t, 0) + 1
    return {"schema": "livesim-registry.v1", "counts": counts, "tests": entries}


def to_yaml(reg: dict) -> str:
    try:
        import yaml  # type: ignore

        return yaml.safe_dump(reg, sort_keys=False, width=100, allow_unicode=True)
    except Exception:
        import json

        return json.dumps(reg, indent=2)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", action="store_true", dest="print_only")
    args = ap.parse_args(argv)
    reg = build()
    text = (
        "# LiveSim test registry — GENERATED by scripts/livesim/gen_registry.py.\n"
        "# Do not edit by hand; regenerate after adding/removing tests.\n"
        "# Definition/command here; actual results + run history in var/livesim/ledger.jsonl;\n"
        "# evidence in var/livesim/evidence/<run_id>/. Contract: docs/testing/LIVESIM.md.\n"
        + to_yaml(reg)
    )
    if args.print_only:
        print(text)
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding="utf-8")
        print(f"[livesim] wrote {OUT} — {reg['counts']['tests']} tests across "
              f"{len(reg['counts']['by_category'])} categories")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
